### ISSUE TITLE
Window用Android ndk r10 编译一个支持tls/ssl的so

### ISSUE THREAD

**Issue by darin-lao** [NetEase/libpomelo2#24]
Window可以用Android ndk r10 直接编译一个支持tls/ssl的so,直接CMD到目录运行ndk-build,有很多问题

**Comment by cynron** [comment]
没明白你在说啥

**Comment by Jennal** [comment]
@darin-lao Android.mk没有做tls/ssl的支持，需要的话自己修改一下Android.mk文件
