### ISSUE TITLE
iOS使用libpomelo2无法初始化客户端

### ISSUE THREAD

**Issue by zhouzizi** [NetEase/libpomelo2#25]
我在object-c项目中使用libpomelo2，不是pomelo。
【http://www.youduoshao.com/2014-11-19/201411192349.html】我根据这篇章编译好了模拟器版和真机版的.a文件并且合并了。将合并好的三个.a添加到项目中，并且添加了pomelo.h文件。但是在项目中无法调用pc_client_t初始化客户端。
1.请问官方有做过相关oc的Demo吗，是否测试在ios oc中可行呢？
2.为什么pomelo.h中的其他方法或者机构体都可以调用，而初始化客户端pc_client_t结构体调用不了？

**Comment by cynron** [comment]
1. ios测试过的，除了openssl编译有问题，没有时间细搞外，造成tls无法使用外，其他都ok
2. 这个不复杂的，直接类似于 pc_client_t* client = (pc_client_t*)malloc(pc_client_size()); 然后pc_client_init即可.

ps: 没有暴露pc_client_t这个结构体的内部，仅仅暴露了这个结构体的大小，这样做的好处是容易做二进制兼容，增减字段啥的，都对用户透明.

**Comment by zhouzizi** [comment]
编译是没问题。是没有写过testDemo吗。我这边编译也可以通过。
我知道直接类似于 pc_client_t* client = (pc_client_t*)malloc(pc_client_size())就可以。但是xcode调用不了pc_client_t这个结构体。use of undeclared identifier找不到这个标识符。

**Comment by cynron** [comment]
测试用例是可以跑通的，没有声明的标识符错误不至于。你可以试着加两条声明看看

```
struct pc_client_s;
typedef struct pc_client_s pc_client_t;
```

**Comment by zhouzizi** [comment]
那太奇怪了，我添加了这行还是调用不了。但是如果把这行typedef struct pc_client_s pc_client_t的pc_client_t前添加个 * 号可以可以识别标识符，是不是c的这种写法swift识别不了？

**Comment by cynron** [comment]
那就不清楚，你搜一下吧

**Comment by zhouzizi** [comment]
都没出一个类似java用的client.java文件给iOS用户，iOS直接调用pomelo.h的方法，各种奇葩的参数，非常不方便。

**Comment by cynron** [comment]
因为在OC中可以直接嵌入C代码，你也可以考虑自己做一个OC的thin binding，这个还是交给用户的好
