### ISSUE TITLE
关于protobuf的一个小问题

### ISSUE THREAD

**Issue by hbbalfred** [NetEase/libpomelo2#29]
由于libpomelo2对于c以外的其它语言采用plugin的形式。
那么当plugin需要使用protobuf来压缩数据时，是不是还要再经过`c`这层来转换数据？

**Comment by cynron** [comment]
没太理解你说的意思。

对于其他语言的使用，实际上是传入一个合法的json，libpomelo2会完成校验及编码，然后发出.

**Comment by hbbalfred** [comment]
对不起，那应该是我理解错了。
我当作是需要客户端自己编译好protobuf，然后把protobuf协议改成json形式的放在服务器端，服务端根据这个协议传递一个二进制下来...看来关系弄反了...所以也就是说pomelo最终是以json来传递，客户端免不了要解析json这样，是吧？
我明白了，非常感谢！

**Comment by cynron** [comment]
pomelo的客户端以及服务端都实现了对protobuf的动态解析，这个是比原生的protobuf要耗，但是因为是动态解析的，所以较方便。

服务端会把protobuf定义传到客户端，然后通信的时候，服务端与客户端都会根据protobuf定义，动态地完成消息的编解码，线上协议是protobuf编码的.
