### ISSUE TITLE
libpomelo2.so for android can't connect to latest chatofpomelo server

### ISSUE THREAD

**Issue by rachelxj** [NetEase/libpomelo2#33]
I tried building libpomelo2.so (version 0.2.0) on both ubuntu 14.04 32-bit and 64-bit, "file libpomelo2.so" shows :
libjpomelo.so: ELF 32-bit LSB  shared object, ARM, EABI5 version 1 (SYSV), dynamically linked (uses shared libs), not stripped

When I tried to test it on android, it shows: (I was using Test.java in the libpomelo2 source code, IP is changed to IP of my local machine)

04-02 05:51:17.798: I/System.out(703): UV Conn Error get push message: null
04-02 05:51:17.807: I/System.out(703): ev_type: PC_EV_CONNECT_ERROR
04-02 05:51:18.787: I/System.out(703): UV Conn Error get push message: null
04-02 05:51:18.807: I/System.out(703): ev_type: PC_EV_CONNECT_ERROR
04-02 05:51:18.818: I/System.out(703): get resp:null
04-02 05:51:23.818: I/System.out(703): UV Conn Error get push message: null
04-02 05:51:23.818: I/System.out(703): ev_type: PC_EV_CONNECT_ERROR
04-02 05:51:34.808: I/System.out(703): UV Conn Error get push message: null
04-02 05:51:34.808: I/System.out(703): ev_type: PC_EV_CONNECT_ERROR

**Comment by cynron** [comment]
CONNECT_ERROR, it means there must be some problem about the networking.

**Comment by rachelxj** [comment]
It works when I used the android client written in Java (https://github.com/NetEase/pomelo-androidclient), which means the network between android and my laptop is good. So I don't know how to fix this connect problem

**Comment by cynron** [comment]
you can run it on an android simulator to test if it works.

**Comment by rachelxj** [comment]
That's what I did, I got that error message.

**Comment by rachelxj** [comment]
Here is the code I used to test on android simulator, pretty much the same as Test.java, except I changed the IP pointing to my laptop
Client.libInit(Client.PC_LOG_WARN, null, null);
Client c = new Client();
c.init(true, false, new Client.LocalStorage() {
    public int write(String s) {
        return -1;
    }
    public String read() {
          return null;
     }
  });
  int result = c.connect("192.168.2.125", 3014);
  int handler_id = c.addEventHandler(new Client.EventHandler() {
	public void handle(int ev_type, String arg1, String arg2) {
		System.out.println(arg1 + " get push message: " + arg2);
		System.out.println("ev_type: " + Client.evToStr(ev_type));
	}
});

try {
	Thread.sleep(1000);
} catch (Exception e) {

}
c.request("gate.gateHandler.queryEntry", "{\"name\":\"999\"}", 5000,
	new Client.RequestCallback() {
		@Override
		public void handle(int rc, String resp) {
			System.out.println("get resp:" + resp);
		}
	});

**Comment by cynron** [comment]
You can capture the packet on your laptop to detect whether the packet is sent out from simulator.

**Comment by rachelxj** [comment]
Which tool should I use to capture the packet? Any more advice? Thanks

**Comment by cynron** [comment]
tcpdump or wireshark is ok, you can try it.

**Comment by rachelxj** [comment]
Actually it works when I used the android client written in Java (https://github.com/NetEase/pomelo-androidclient), the network should be fine, so I don't know what exactly I should look into.

**Comment by cynron** [comment]
You can debug  libpomelo2.so to see what happened when connecting to server.

I can not provide more help without detail.

**Comment by rachelxj** [comment]
I don't know how to debug libpomelo2.so from android device. never mind. I gave up

**Comment by angrycans** [comment]
I also have this problem .
Android can not use lib

**Comment by angrycans** [comment]
Who can build libjpomelo.so for android?

**Comment by angrycans** [comment]
I find the problem is.

c.init(true, false, new Client.LocalStorage() {

change 

c.init(false, false, new Client.LocalStorage() {


because .   NO_TLS
 if (enable_tls) {
        config.transport_name = PC_TR_NAME_UV_TLS;
    }

**Comment by yuzhaoshi** [comment]
Thank you!
