### ISSUE TITLE
对于request请求，服务端返回response消息，无法进行压缩

### ISSUE THREAD

**Issue by s0oo** [NetEase/libpomelo2#35]

**Comment by s0oo** [comment]
比如在chatofpomelo中，在服务端的serverProtos.json中添加：
"gate.gateHandler.queryEntry": {
    "required uInt32 code": 1,
    "required string host": 2,
    "required uInt32 port": 3
  }
客户端请求时，服务端会发送压缩后的消息。
gate.gateHandler.queryEntry = function(msg, session, next) {
    next(null, {
        code: 200,
        host: res.host,
        port: res.clientPort
    });
};
然后，客户端会收到压缩过的消息，无法解析。
在C#的客户端中是可以解析的。

**Comment by cynron** [comment]
见 #23 ，这个问题不打算修了

**Comment by frankqianghe** [comment]
服务端返回protobuf压缩的response，客户端无法解析，如果服务器端主动推送的信息，经过protobuf压缩，客户端是否可以解析

**Comment by Jennal** [comment]
@cynron 这个问题会不会拖太久了？到现在都没有解决的方案吗？
