### ISSUE TITLE
服务端返回protobuf压缩的response，客户端无法解析，如果服务器端主动推送的信息，经过protobuf压缩，客户端是否可以解析

### ISSUE THREAD

**Issue by frankqianghe** [NetEase/libpomelo2#36]
就是直接用
channel.pushMessage
发送的信息，如果是经过protobuf压缩的，客户端收到后能正常解析吗

**Comment by cynron** [comment]
在 #23 中已经详细论述过这个问题，直接push是不受影响的。主要原因是resp里面不带route信息，这个是协议设计的缺陷。
