### ISSUE TITLE
字符集和字符编码问题

### ISSUE THREAD

**Issue by tweyseo** [NetEase/libpomelo2#37]
因为我这边UI到客户端上层的出口和客户端上层到UI的出口都是GBK的字符集 可是libpoemlo2底层又不支持GBK的字符集 所以我在递给libpoemlo2的时候 就转成了unicode(eg:"\\u1234"),然后libpoemlo2底层又转一次(还是unicode,叫它"naxx"吧)然后发给服务器,服务器内部是可以正常显示汉字了,可是在libpoemlo2的recieved里decode的时候没有给我转回成我之前递给他unicode(eg:"\\u1234"),而是"naxx",这个时候我再递给我的中间层unicode转GBK的时候 就是乱码了,理论上讲这个过程应该是对称的才对呀

**Comment by cynron** [comment]
已经在 http://nodejs.netease.com/topic/553f520e710651e80f14a39d#55484007710651e80fd3530a  回答了，这个实际上与libpomelo2无关，跟json规范有关，你的unicode转gbk的转码程序，应该能够同时处理 utf8 字节流以及\uXXXX 表示的unicode码。
