### ISSUE TITLE
请问不依赖libuv的libpomelo2版本有时间计划吗？

### ISSUE THREAD

**Issue by hankchan** [NetEase/libpomelo2#40]
目前我们准备在一个MCU项目中使用pomelo，客户端可以使用websocket、socket.IO、MQTT。
除此以外，我们之前关注到libpomelo2在准备不依赖libuv的版本，请问该版本有时间计划吗？
谢谢。

**Comment by cynron** [comment]
有计划，但是没有ETA

原因： 时间，精力，稳定性

**Comment by hankchan** [comment]
非常感谢！
