### ISSUE TITLE
support visual studio 2015 on window

### ISSUE THREAD

**Issue by wayne5ning** [NetEase/libpomelo2#43]

**Comment by cynron** [comment]
so, any problem for vs 2015 ?

**Comment by wayne5ning** [comment]
When I tried to run "npm install pomelo -g", a compilation error occurred. With installation of VS2010 Express, "npm install pomelo -g" works fine.

**Comment by cynron** [comment]
It is pomelo or nodejs' business, not libpomelo2. Closing here, :)
