### ISSUE TITLE
When can't connect to server, it will assert failed after call pc_client_disconnect.

### ISSUE THREAD

**Issue by zihuyishi** [NetEase/libpomelo2#47]
I use libpomelo2 in an iOS app. I wan't close connection when app enter background. So I write this code when app enter background.
```cpp
    for (int i = 0; i < m_count; ++i) {
        if (m_pomelos[i] != nullptr) {
            pc_client_disconnect(m_pomelos[i]);
            pc_client_rm_ev_handler(m_pomelos[i], m_event_handler);
            pc_client_cleanup(m_pomelos[i]);
            free(m_pomelos[i]);
            m_pomelos[i] = nullptr;
        }
    }
```
Sometime our server is offline for test, so the connection will always timeout.
And it will assert fail in file [pc_trans.c](https://github.com/NetEase/libpomelo2/blob/master/src/pc_trans.c#L111).

Maybe there something wrong in my code, so I need some help.

**Comment by zihuyishi** [comment]
我发现是在libuv的[代码](https://github.com/NetEase/libpomelo2/blob/master/deps/uv/src/unix/stream.c#L428)里，关闭连接后，如果之前连接失败，就会走近if语句里
```cpp
  if (stream->connect_req) {
    uv__req_unregister(stream->loop, stream->connect_req);
    stream->connect_req->cb(stream->connect_req, -ECANCELED);
    stream->connect_req = NULL;
  }
```
此时会调用xxx__conn_done_cb方法，其实此时我已经主动断开连接了，所以触发PC_EV_CONNECT_ERROR时就会判断出错。
并且tcp__conn_done_cb方法最后还会调用重连，还会导致程序崩溃。

**Comment by cynron** [comment]
这里涉及到一个异步调用,释放的问题.

简单的一个方法, 就是调用完disconnect后,加一个sleep即可,也就是保证对应的回调调用完后,再往下继续.

这个问题的原因是由于依赖了libuv导致的, 必须按照libuv的哲学编程.

你可以试一下,加一个sleep的方法,sleep的时间,一秒以内就应该是ok的

**Comment by zihuyishi** [comment]
好吧，我明天去试试。

**Comment by cynron** [comment]
加sleep的方法,是一种比较懒的处理方式.

理论上的处理方式是,等待,直到对应的disconnect事件回调以后,再给这边发信号,再继续,执行下面的清理操作.

不过这种写法比较复杂,实际应用中可能加sleep是最简单有效地了

**Comment by zihuyishi** [comment]
我试了下sleep并没有解决问题。
现在的问题是在uv__stream_destroy里面会调用tcp__conn_done_cb,此时的处理是当作PC_EV_CONNECT_ERROR。
我试着将[此处](https://github.com/NetEase/libpomelo2/blob/master/src/tr/uv/tr_uv_tcp_aux.c#L351)的代码改成
```cpp
    if (status == UV_ECANCELED) {
        pc_lib_log(PC_LOG_DEBUG, "tcp__conn_done_cb - connect cancel");
        pc_trans_fire_event(tt->client, PC_EV_CANCEL, "Connect Cancel", NULL);
        return ;
    }
    else {
        pc_lib_log(PC_LOG_DEBUG, "tcp__conn_done_cb - connect error, error: %s", uv_strerror(status));
        pc_trans_fire_event(tt->client, PC_EV_CONNECT_ERROR, "Connect Error", NULL);
    }
```
头文件中
```cpp
#define PC_EV_CANCEL
```
也就是增加了一个对取消的处理，看起来就没什么问题了。
但是因为对libuv不太熟悉，不知道这么改会不会影响重连？
