### ISSUE TITLE
IOS上使用时，经常出现Assertion failed: (stream->write_queue_size >= len), function uv__write

### ISSUE THREAD

**Issue by caotian** [NetEase/libpomelo2#51]
IOS上使用时，连接的本机pomelo。经常在重新运行时出现这个错误：
Assertion failed: (stream->write_queue_size >= len), function uv__write, file /Users/XXXXXXXX/XXX/XXXXX/lib/libpomelo2/deps/uv/src/unix/stream.c, line 870. 
再次运行就没问题了。
发生的机率还是比较高，有可能是什么原因？

**Comment by cynron** [comment]
这个堆栈在libuv内部，很有可能是libuv的bug，可以尝试升级一下libuv

看看能不能抽出来一个高概率重现的最小测试用例？

**Comment by cynron** [comment]
没有堆栈吗？我们根本没办法重现这样的问题，还是需要崩溃时，你们抓点堆栈，无论是libuv的问题，还是libpomelo2的问题，我都可以修的

**Comment by cynron** [comment]
ping
