### ISSUE TITLE
Assertion failed in function uv_close() when cleanup a PC_ST_INITED client.

### ISSUE THREAD

**Issue by xpol** [NetEase/libpomelo2#56]
I'm test my [lua bindings for libpomelo2](https://github.com/xpol/lua-pomelo).
When I running unit test: create a client without connect, then I got

> Assertion failed: (0), function uv_close, file [src/unix/core.c, line 165](https://github.com/libuv/libuv/blob/v1.8.0/src/unix/core.c#L165).

*I linked with the latest libuv 1.8.0.*

**Comment by xpol** [comment]
C code that reproduce the bug:
```c
void test_c()
{
    pc_client_t* client = (pc_client_t*)malloc(pc_client_size());
    pc_client_config_t config = PC_CLIENT_CONFIG_DEFAULT;
    pc_lib_init(NULL, NULL, NULL, "Test Client");
    pc_client_init(client, NULL, &config);
    pc_client_cleanup(client);
}
```

**Comment by cynron** [comment]
Goto #57
