### ISSUE TITLE
事件宏的时态不一致

### ISSUE THREAD

**Issue by xpol** [NetEase/libpomelo2#64]
* PC_EV_CONNECTED: 过去时
* PC_EV_DISCONNECT: 一般现在时
* PC_EV_KICKED_BY_SERVER: 过去时

Nodejs 的 [net.Socket](https://nodejs.org/dist/latest-v4.x/docs/api/net.html#net_class_net_socket) 事件是用的一般现在时，比如 `connect`, `close`.

**Comment by cynron** [comment]
这个connected跟kicked_by 都是被动完成时
